/*
 * InformasiLabirin.java
 *
 * Created on February 18, 2008, 12:03 PM
 */



/**
 *
 * @author  Ade Azurat
 */
public class InformasiLabirin extends javax.swing.JDialog {
    String location;
    String title;
    
    /** Creates new form InformasiLabirin */
    public InformasiLabirin(java.awt.Frame parent, boolean modal, String titlee, String name) {
        super(parent, modal);           //call the constructor of parent class with 2 parameter
        location = name;                //set the string location of bundle
        title = titlee;                 //set the title of topic
        initComponents();               //initialising all the component
        setSize(555, 450);              //set size of window
        setTitle("Informasi");
        setResizable(false);            //set the resizeable false
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();                  //make object to show the title
        labelInformasi = new javax.swing.JLabel();              //make object to show the information
        scrollPaneInformasi = new javax.swing.JScrollPane();    //make the scroll object
        textInformasi = new javax.swing.JTextArea();            //the area to show the information
        selesai = new javax.swing.JButton();                    //button for close window

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);     //if we clicked close(red cross), the program won't terminated
        getContentPane().setLayout(null);

        labelTitle.setFont(new java.awt.Font("Bradley Hand ITC", 0, 18));
        labelTitle.setText("Kura-kura dalam labirin");                          //set the title "Kura-kura dalam labirin"
        getContentPane().add(labelTitle);
        labelTitle.setBounds(160, 0, 191, 24);

        labelInformasi.setFont(new java.awt.Font("Book Antiqua", 0, 14));
        labelInformasi.setText(title);                                          //set label title
        getContentPane().add(labelInformasi);
        labelInformasi.setBounds(160, 30, 202, 17);

        textInformasi.setColumns(20);
        textInformasi.setLineWrap(true);    //set to wrap the text
        textInformasi.setRows(5);           //set scroll to show 5 rows if scrolled
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Kurakuraku"); // NOI18N
        textInformasi.setText(bundle.getString(location)); // NOI18N
        textInformasi.setEditable( false );
        scrollPaneInformasi.setViewportView(textInformasi);

        getContentPane().add(scrollPaneInformasi);
        scrollPaneInformasi.setBounds(20, 50, 510, 300);

        selesai.setFont(new java.awt.Font("Arial", 0, 11));                 //set atribute of button "selesai"
        selesai.setText("Selesai");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(selesai);
        selesai.setBounds(450, 360, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        setVisible(false);                      //set this window to unvisible
}//GEN-LAST:event_selesaiActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelInformasi;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JScrollPane scrollPaneInformasi;
    private javax.swing.JButton selesai;
    private javax.swing.JTextArea textInformasi;
    // End of variables declaration//GEN-END:variables
    
}
